package calculadora.view;


//ATIVIDADE 2 DAD  
//ALUNO: LUCAS LIMA BRITO
//MATRICULA: 20210054TADS 


import calculadora.controller.CalculadoraController;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lucas Brito
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNum1 = new javax.swing.JTextField();
        jTFNum2 = new javax.swing.JTextField();
        jTFRes = new javax.swing.JTextField();
        jBSoma = new javax.swing.JButton();
        jBSubitracao = new javax.swing.JButton();
        jBMultiplicacao = new javax.swing.JButton();
        jBDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRIMEIRA CALCULADORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SimSun", 3, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setToolTipText("Primeira Calculadora");

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Numero1*");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Numero2*");

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Resultado:");

        jTFNum1.setForeground(new java.awt.Color(0, 51, 255));
        jTFNum1.setToolTipText("");
        jTFNum1.setCaretColor(new java.awt.Color(51, 0, 204));
        jTFNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNum1ActionPerformed(evt);
            }
        });

        jTFNum2.setForeground(new java.awt.Color(0, 51, 255));
        jTFNum2.setToolTipText("");
        jTFNum2.setCaretColor(new java.awt.Color(51, 0, 204));

        jTFRes.setEditable(false);
        jTFRes.setForeground(new java.awt.Color(0, 51, 255));
        jTFRes.setToolTipText("");
        jTFRes.setCaretColor(new java.awt.Color(51, 0, 204));

        jBSoma.setBackground(new java.awt.Color(255, 255, 255));
        jBSoma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBSoma.setForeground(new java.awt.Color(255, 0, 0));
        jBSoma.setMnemonic('B');
        jBSoma.setText("+");
        jBSoma.setToolTipText("botao novo em java");
        jBSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaActionPerformed(evt);
            }
        });

        jBSubitracao.setBackground(new java.awt.Color(255, 255, 255));
        jBSubitracao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBSubitracao.setForeground(new java.awt.Color(255, 0, 0));
        jBSubitracao.setText("-");
        jBSubitracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubitracaoActionPerformed(evt);
            }
        });

        jBMultiplicacao.setBackground(new java.awt.Color(255, 255, 255));
        jBMultiplicacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBMultiplicacao.setForeground(new java.awt.Color(255, 51, 51));
        jBMultiplicacao.setText("x");
        jBMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicacaoActionPerformed(evt);
            }
        });

        jBDivisao.setBackground(new java.awt.Color(255, 255, 255));
        jBDivisao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBDivisao.setForeground(new java.awt.Color(255, 0, 0));
        jBDivisao.setText("/");
        jBDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFRes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jBSoma, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSubitracao, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSubitracao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaActionPerformed
        if (ValidaEntradas() == true) {
            String num1 = jTFNum1.getText();
            Float n1 = retornaValorNumericoCampo(jTFNum1.getText());
            Float n2 = retornaValorNumericoCampo(jTFNum2.getText());
            Float res = CalculadoraController.soma(n1, n2);

            jTFRes.setText(res.toString());
        }
    

    }//GEN-LAST:event_jBSomaActionPerformed


    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here: 
    }//GEN-LAST:event_formKeyPressed

    private void jBSubitracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubitracaoActionPerformed

         if (ValidaEntradas() == true) {
            String num1 = jTFNum1.getText();
        Float n1 = retornaValorNumericoCampo(jTFNum1.getText());
        Float n2 = retornaValorNumericoCampo(jTFNum2.getText());
        Float res = CalculadoraController.subtracao(n1, n2);
        jTFRes.setText(res.toString());
    }//GEN-LAST:event_jBSubitracaoActionPerformed
    }
    private void jBDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisaoActionPerformed
         if (ValidaEntradas() == true) {
            String num1 = jTFNum1.getText();
        
        Float n1 = retornaValorNumericoCampo(jTFNum1.getText());
        Float n2 = retornaValorNumericoCampo(jTFNum2.getText());
        Float res = CalculadoraController.divisao(n1, n2);
        jTFRes.setText(res.toString());
    }//GEN-LAST:event_jBDivisaoActionPerformed
    }
    private void jTFNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNum1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTFNum1ActionPerformed

    private void jBMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicacaoActionPerformed
         if (ValidaEntradas() == true) {
            String num1 = jTFNum1.getText();
        
        Float n1 = retornaValorNumericoCampo(jTFNum1.getText());
        Float n2 = retornaValorNumericoCampo(jTFNum2.getText());
        Float res = CalculadoraController.multiplicacao(n1, n2);
        jTFRes.setText(res.toString());
         }
    }//GEN-LAST:event_jBMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDivisao;
    private javax.swing.JButton jBMultiplicacao;
    private javax.swing.JButton jBSoma;
    private javax.swing.JButton jBSubitracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFNum1;
    private javax.swing.JTextField jTFNum2;
    private javax.swing.JTextField jTFRes;
    // End of variables declaration//GEN-END:variables
private Float retornaValorNumericoCampo(String texto) {
        Float val = Float.parseFloat(texto);
        return val;
    }

    private Boolean ValidaEntradas() {
        if (jTFNum1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo[numéro 1] nao poder ser vazio!");
            jTFNum1.grabFocus();
            return false;
        } else if (jTFNum2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo[numéro 2] nao poder ser vazio!");
             jTFNum2.grabFocus();
            return false;
        } else {
            return true;
        }
    }

}
